#include "GenerationMethods.h"
#include <iostream>

using namespace std;

//note: ctor is short for "constructor"
//this is automatically generated by codeblocks
//Moreover, the double colons here state the GenerationMethods() constructor belongs to the GenerationMethods class
GenerationMethods::GenerationMethods()
{
    //ctor
}

    void introMessage() {
        cout << "Please begin typing arguments as one string or type '!help' for help" << endl;
    }
